In [1]:
from gridworld import *
import numpy as np


In [2]:
world_size = (6,5)
starting_point = (2,4)
destinations = [(2,2),(2,0)]
obstacles = [(1,1),(2,1),(1,3),(2,3)]
hazards = [(4,0),(4,1),(4,2),(4,3),(4,4)]

world = gridworld(world_size,starting_point,destinations,obstacles,hazards,p_e=0.4,dest_rewards=[1,10],haz_rewards=-10,dest_names=['diddy reese','safron rose'],gamma=.7)

world.print_policy_map()
world.states

[['↓' '←' '←' '←' '←' '↓']
 ['↓' 'o' 'o' '↓' '←' '↓']
 ['↓' '→' 'o' '↓' '←' '↓']
 ['↓' 'o' 'o' '↓' '←' '↓']
 ['→' '→' 'o' '←' '←' 'o']]
[[24. 25. 26. 27. 28. 29.]
 [18. 19. 20. 21. 22. 23.]
 [12. 13. 14. 15. 16. 17.]
 [ 6.  7.  8.  9. 10. 11.]
 [ 0.  1.  2.  3.  4.  5.]]
