In [ ]:
from control import dlqr
import numpy as np

A = np.array([[1,1],[0,1]])
B = np.array([[0],[1]])
y_max = 10
v_max = 5
f_max = 3
g_y = 1
g_v = 1
g_f = 1
Q = np.diag([g_y/(y_max**2),g_v/(v_max**2)])
R = np.array(g_f/(f_max**2))
out = dlqr(A,B,Q,R)
K = out[0]
S = out[1]
print("S=",S)
print("K=",K)

In [1]:
from numberline.numberline import *
x = np.array([[1],[0]])
w = np.array([[0]])
B_w = np.array([[0],[1]])
for i in range(10):
    print(x)
    x = timestep(x,K,w,A,B,B_w)
print(x)

[[1]
 [0]]
[[-0.184059]]
[[1]
 [0]]
[[ 0.      ]
 [-0.184059]]
[[0]
 [0]]
[[ 1.      ]
 [-0.184059]]
[[-0.0354056]]
[[ 0.815941]
 [-0.184059]]
[[ 0.       ]
 [-0.0354056]]
[[0]
 [0]]
[[ 0.815941 ]
 [-0.2194646]]
[[0.02706709]]
[[ 0.5964764]
 [-0.2194646]]
[[0.        ]
 [0.02706709]]
[[0]
 [0]]
[[ 0.5964764 ]
 [-0.19239751]]
[[0.04560106]]
[[ 0.40407889]
 [-0.19239751]]
[[0.        ]
 [0.04560106]]
[[0]
 [0]]
[[ 0.40407889]
 [-0.14679645]]
[[0.04418432]]
[[ 0.25728244]
 [-0.14679645]]
[[0.        ]
 [0.04418432]]
[[0]
 [0]]
[[ 0.25728244]
 [-0.10261213]]
[[0.03551851]]
[[ 0.15467031]
 [-0.10261213]]
[[0.        ]
 [0.03551851]]
[[0]
 [0]]
[[ 0.15467031]
 [-0.06709362]]
[[0.02571903]]
[[ 0.08757668]
 [-0.06709362]]
[[0.        ]
 [0.02571903]]
[[0]
 [0]]
[[ 0.08757668]
 [-0.0413746 ]]
[[0.0172965]]
[[ 0.04620209]
 [-0.0413746 ]]
[[0.       ]
 [0.0172965]]
[[0]
 [0]]
[[ 0.04620209]
 [-0.0240781 ]]
[[0.01094252]]
[[ 0.02212399]
 [-0.0240781 ]]
[[0.        ]
 [0.01094252]]
[[0]
 [0]]
[[ 0.